'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DB_type_SQLServer")>  _
        Public ReadOnly Property Selected_DB_type() As String
            Get
                Return CType(Me("Selected_DB_type"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Server=respdbtest;Database=RespDB;User Id=RespDB;Password=l!$ug50NbjtE;")>  _
        Public ReadOnly Property ConnectionString_SQLServer_MonashMC() As String
            Get
                Return CType(Me("ConnectionString_SQLServer_MonashMC"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\peter\Me\VB.NET applicatio"& _ 
            "ns\ResLab.Net\RespDB.accdb; User Id=admin; Password=;")>  _
        Public ReadOnly Property ConnectionString_Access() As String
            Get
                Return CType(Me("ConnectionString_Access"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MicrosoftAccess")>  _
        Public ReadOnly Property DB_type_Access() As String
            Get
                Return CType(Me("DB_type_Access"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SQLServer")>  _
        Public ReadOnly Property DB_type_SQLServer() As String
            Get
                Return CType(Me("DB_type_SQLServer"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MySQL")>  _
        Public ReadOnly Property DB_type_MySQL() As String
            Get
                Return CType(Me("DB_type_MySQL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\temp\")>  _
        Public ReadOnly Property DefaultFolder_SavePDF() As String
            Get
                Return CType(Me("DefaultFolder_SavePDF"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Server=PETE\SQLExpress;Trusted_connection=Yes;Database=ResLabDB_heavy;")>  _
        Public ReadOnly Property ConnectionString_SQLServer_MyLaptop() As String
            Get
                Return CType(Me("ConnectionString_SQLServer_MyLaptop"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ConnectionString_SQLServer_Austin")>  _
        Public ReadOnly Property Selected_ConnectionString() As String
            Get
                Return CType(Me("Selected_ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("04/11/2016")>  _
        Public ReadOnly Property BuildDate() As String
            Get
                Return CType(Me("BuildDate"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0 Heavy")>  _
        Public ReadOnly Property Version() As String
            Get
                Return CType(Me("Version"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Server=HNESQLDEV01;Database=ResLabDB_SQL;User Id=RespLab_User;Password=resplab$us"& _ 
            "er;")>  _
        Public ReadOnly Property ConnectionString_SQLServer_JohnHunter() As String
            Get
                Return CType(Me("ConnectionString_SQLServer_JohnHunter"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Server=EHTESTSQL12_API;Database=RespDB_SQL_Test;User Id=respdb_sqluser;Password=e"& _ 
            "hrespdbuser;")>  _
        Public ReadOnly Property ConnectionString_SQLServer_BoxHillHospital() As String
            Get
                Return CType(Me("ConnectionString_SQLServer_BoxHillHospital"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Server=ahacsql01;Database=RespDB;User Id=respdb;Password=RespAdmin2015;")>  _
        Public ReadOnly Property ConnectionString_SQLServer_Alfred() As String
            Get
                Return CType(Me("ConnectionString_SQLServer_Alfred"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("donotenter")>  _
        Public ReadOnly Property Password_hidden() As String
            Get
                Return CType(Me("Password_hidden"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Password_userset() As String
            Get
                Return CType(Me("Password_userset"),String)
            End Get
            Set
                Me("Password_userset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Server=localhost\SQLExpress;Trusted_connection=Yes;Database=ResLabDB_heavy;")>  _
        Public Property ConnectionString_SQLServer_Austin() As String
            Get
                Return CType(Me("ConnectionString_SQLServer_Austin"),String)
            End Get
            Set
                Me("ConnectionString_SQLServer_Austin") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ResLab_V1_Heavy.My.MySettings
            Get
                Return Global.ResLab_V1_Heavy.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
